### ISSUE TITLE
Feature: make buckets configurable per host group

### ISSUE THREAD

**Issue by mlazowik** [SuperQ/smokeping_prober#63]
Use case: monitoring hosts from different geo locations without giving up on granular resolution.

**Comment by SuperQ** [comment]
Thinking about this more, I'm not sure this is something we can do easily. The problem is that metrics registration with the client library happens once. In order to register different buckets, the metric would need to be registered multiple times.

This isn't valid per metrics registry. We could create multiple registries, but that may be tricky to do in a valid way in a single scrape endpoint.
